pubkey-sh:
  build: '.'
  environment:
    DATASOURCE_LOGIN: ''
    DATASOURCE_PASS:  ''
    DATASOURCE_PATH:  'sqlite:/data/pubkey.db'
    HALITE_KEYFILE:   '/data/halite.key'
    HTTP_PORT:        '8080'
    HTTPS_PORT:       '1443'
    SERVER_NAME:      'pubkey.sh'
    SESSION_EXPIRE:   '1800'
  ports:
    - '8080'
    - '1443'
